### ISSUE TITLE
CSSフレームワークを選ぶ

### ISSUE THREAD

**Issue by YasukeXXX** [YasukeXXX/processor#4]
http://tetra-themes.com/sass-framework-mixins-425/

**Comment by YasukeXXX** [comment]
uikit使おうと思っていたけどTKD氏が使うみたいなのでやめた。

https://semantic-ui.com/
これにする気がする

**Comment by koheisg** [comment]
選定基準www

**Comment by YasukeXXX** [comment]
@koheisg 
こういうの何を基準に選べばいいかわからないですね〜
情報の多さとかですかね?

**Comment by koheisg** [comment]
simple と easy のバランスだけど、

simple さを理解するのは結構難しい。
例えば、cssに対する知見や経験が必要。

easyは使ってみて自分にあってるかどうか、ある程度直感で決められるかな。

その点 rails はすごい simpleさとeasyさを両立してるように今の僕には思えるから、
javascript周りには正直不満があるけど、改善していってるしね。

**Comment by koheisg** [comment]
日報読んだけど、良さそうって直感あるみたいだから、選定基準としては良さそうと思った

**Comment by YasukeXXX** [comment]
@koheisg 
easyさで選ぶにしても、ちょっと使って見ないとわからないですよね。
雰囲気良さそうと感じたので、とりあえずこれつかってみます！
ありがとうございます！

**Comment by koheisg** [comment]
そういえば、これちょっと気になってる。

https://getmdl.io/

**Comment by YasukeXXX** [comment]
@koheisg 
もう少し早く知りたかた...🐼

**Comment by koheisg** [comment]
気になり始めたのが今朝なもんでw

**Comment by YasukeXXX** [comment]
@koheisg 
こちらは今朝これ使い始めてZOZOTOWNになったところです。
<img width="1143" alt="2017-07-18 18 19 42" src="https://user-images.githubusercontent.com/11922057/28309902-bfbb4e6a-6be5-11e7-800f-e4a1ae739358.png">
